# Travis Continuous Integration Configuration File For ROS Control Projects
sudo: required
dist: trusty
language: generic

notifications:
  email:
    recipients:
      - enrique.fernandez.perdomo@gmail.com
      - bence.magyar.robotics@gmail.com
      - gennaro.raiola@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    - ROS_PARALLEL_TEST_JOBS=-j1
  matrix:
    - ROS_DISTRO=melodic  ROS_REPO=ros              UPSTREAM_WORKSPACE=https://raw.github.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall
    - ROS_DISTRO=melodic  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=https://raw.github.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall
  
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
- .ci_config/travis.sh
