name: ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2-master

jobs:
  abi_check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@use_containers
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, jazzy, iron, humble]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
