name: Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source_build:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    strategy:
      matrix:
        ROS_DISTRO: [rolling, iron, humble]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ref: ros2-master
      ros2_repo_branch: ${{ matrix.ROS_DISTRO }}
