# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Downstream Build
on:
  pull_request:
  push:
    branches:
      - ros2-master


jobs:
  build-downstream:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, jazzy, humble]
        ROS_REPO: [testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      ref_for_scheduled_build: ros2-master
      not_test_build: true
      downstream_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      not_test_downstream: true
