name: Humble - ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble

jobs:
  abi_check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@upload_abi_logs
    with:
      ros_distro: humble
