name: Humble - RHEL Semi-Binary Build
on:
  workflow_dispatch:


jobs:
  rhel_semi_binary_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rhel-binary-build.yml@master
    with:
      ros_distro: humble
      upstream_workspace: control_toolbox.humble.repos
      ref_for_scheduled_build: humble
