name: Humble - Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble

jobs:
  source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@test/cmake
    with:
      ros_distro: humble
      ref: humble
      ros2_repo_branch: humble
      os_name: ubuntu-22.04
      container: ""
