name: Humble - Debian Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 5 * * *'


jobs:
  debian_source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: humble
      upstream_workspace: control_toolbox.humble.repos
      ref_for_scheduled_build: humble
