name: Humble - Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * MON-FRI'

jobs:
  source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: humble
      ref: humble
      os_name: ubuntu-22.04
      container: ""
