name: Humble - ABI Compatibility Check
on:
  workflow_dispatch:

jobs:
  abi_check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@master
    with:
      ros_distro: humble
