name: RHEL Iron Semi-Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'


jobs:
  iron_rhel:
    name: Iron RHEL semi-binary build
    uses: ./.github/workflows/reusable-rhel-binary-build.yml
    with:
      ros_distro: iron
      upstream_workspace: control_toolbox.iron.repos
      ref_for_scheduled_build: ros2-master
