name: Debian Iron Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 5 * * *'


jobs:
  iron_debian:
    name: Iron debian build
    uses: ./.github/workflows/reusable-debian-build.yml
    with:
      ros_distro: iron
      upstream_workspace: control_toolbox.iron.repos
      ref_for_scheduled_build: ros2-master
