name: Jazzy - Coverage Build
on:
  workflow_dispatch:
  push:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/jazzy-build-coverage.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xml'
  pull_request:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/jazzy-build-coverage.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xml'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  coverage:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: jazzy
