# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Jazzy - Downstream Build
on:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy


jobs:
  build-downstream:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      ref_for_scheduled_build: jazzy
      not_test_build: true
      upstream_workspace: control_toolbox.jazzy.repos
      # we test the downstream packages, which are part of our organization
      downstream_workspace: ros_controls.jazzy.repos
      not_test_downstream: false
