# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Jazzy - Semi-Binary Build
on:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * *'


jobs:
  semi-binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      upstream_workspace: control_toolbox.jazzy.repos
      ref_for_scheduled_build: jazzy
