# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: Jazzy - Binary Build
on:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '28 6 * * MON-FRI'


jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: jazzy
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: control_toolbox-not-released.jazzy.repos
      ref_for_scheduled_build: jazzy
  binary_clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      upstream_workspace: control_toolbox-not-released.jazzy.repos
      ref_for_scheduled_build: jazzy
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
