name: Jazzy - Coverage Build
on:
  workflow_dispatch:
  push:
    branches:
      - jazzy
  pull_request:
    branches:
      - jazzy

jobs:
  coverage:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: jazzy
