name: Jazzy - Debian Semi-Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 5 * * MON-FRI'


jobs:
  debian_semi_binary_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    with:
      ros_distro: jazzy
      upstream_workspace: control_toolbox.jazzy.repos
      ref_for_scheduled_build: jazzy
