name: Jazzy - ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy

jobs:
  abi_check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-abi-check.yml@master
    with:
      ros_distro: jazzy
