name: Kilted - Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - kilted
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/kilted-build-source.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xml'
  pull_request:
    branches:
      - kilted
    paths:
      - .github/workflows/kilted-build-source.yml
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: kilted
      ref: kilted
      container: ubuntu:24.04
