name: Debian Rolling Source Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - ros2-master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 5 * * *'


jobs:
  rolling_debian:
    name: Rolling debian build
    uses: ./.github/workflows/reusable-debian-build.yml
    with:
      ros_distro: rolling
      upstream_workspace: control_toolbox.rolling.repos
      ref_for_scheduled_build: ros2-master
